cd soundex
cd stage1
python soundex1a.py
python soundex1b.py
python soundex1c.py
python soundex1d.py
python soundex1e.py
cd ..
cd stage2
python soundex2a.py
python soundex2b.py
python soundex2c.py
cd ..
cd stage3
python soundex3a.py
python soundex3b.py
python soundex3c.py
python soundex3d.py
cd ..
cd stage4
python soundex4a.py
python soundex4b.py
python soundex4c.py
python soundex4d.py
